### ISSUE TITLE
tailwindcss 로 컨테이너 너비에 반응하는 NextImage 컴포넌트 만들기

### ISSUE THREAD

**Issue by e2goon** [e2goon/powerjade#24]
## 배경

제 블로그에 `next/image` 컴포넌트를 사용했습니다. 실제로 이 컴포넌트를 활용해서 디자이너의 요구사항대로 처리하기 어려운 상황을 경험했을 거라고 생각합니다. 이 컴포넌트의 단점은 이미지의 너비가 줄어들 때 너비와 높이의 비율을 유지할 수 없는 상황에 제약이 있었고, 이미지의 모서리를 라운드 처리하는데 어려움이 있었습니다.

조건은 다음과 같습니다.

- 좌우 너비가 브라우저 크기 혹은 컨테이너 크기에 따라 유동적으로 변하기
- `<img />` 태그와 동일한 사용 경험을 얻기
- 모서리에 Round 효과 주기

이 세가지를 만족할 수 있는 결과를 얻기 위해 `next/image` 컴포넌트에 CSS 코드를 오버라이딩 해야합니다. 인라인 스타일이 포함되어 있기 떄문에 CSS 우선 순위를 무시하고 제가 작성한 CSS 코드가 우선 적용 되어야 합니다.

```tsx
import Image from 'next/image';

<span className="next-image">
  <Image src={src} alt={alt} layout="fill" />
</span>
```

```css
.next-image {
  display: block;
  width: 100%;
}
.next-image > span {
  position: static;
}
.next-image img {
  position: relative !important;
  width: 100% !important;
  height: auto !important;
  object-fit: contain;
}
```

## tailwindcss 에서 작성하기 

위 코드는 기존 `next/image` 컴포넌트의 스타일을 일부 무력화하면서, `<img />` 태그처럼 사용하게 하는 방법입니다. 하지만, tailwindcss 를 섞어서 사용하는 경우 다음 처럼 작성하면 됩니다.

```css
@layer components {
  .next-image {
    @apply block w-full;

    > span {
      @apply !static;
    }

    img {
      @apply !relative !w-full !h-auto object-contain;
    }
  }
}
```

### 주의사항

앞서 적은 tailwindcss 코드는 초기 설정 시 nesting 문법을 지원하지 않기 때문에 postcss.config.js 설정 파일에 CSS 중첩 문법을 사용하기 위한 별도의 설정 과정이 필요합니다.

```js
// postcss.config.js

module.exports = {
  plugins: {
    "tailwindcss/nesting": {}, // <<< 추가
    tailwindcss: {},
    autoprefixer: {},
  },
```

## 적용 결과

![next/image 컴포넌트 수정](https://user-images.githubusercontent.com/45934/190912248-4cbdc0d3-6979-48ff-8c82-a6bd0546073b.png)

결과적으로 이 이미지는 컨테이너의 너비에 따라 유동적으로 늘어나고 줄어들고, 모서리에 라운드 효과가 적용된 것을 확인할 수 있었습니다.
