### ISSUE TITLE
스크롤바를 감추는 CSS 유틸리티

### ISSUE THREAD

**Issue by e2goon** [e2goon/powerjade#9]
![image](https://user-images.githubusercontent.com/45934/131271279-e78ffb05-ff3e-422b-9c9a-5c4dfe4c110b.png)

스크롤바의 형태를 감추려는 시도 하면 콘텐츠를 탐색할 때 내용을 어디까지 확인했는지 인지하기 어려워집니다. 그럼에도 불구하고 우리는 스크롤바를 감춰야 할 케이스가 있습니다.

모든 브라우저에 일관된 스크롤바 디자인을 적용하기 위해 커스텀하기 위한 용도로 쓰일 때가 있습니다. 자바스크립트를 로딩하는 과정에서 기본 스크롤바의 모양이 깜짝 등장했다가 스크립트가 실행되면 커스텀된 스크롤바 디자인이 입혀지게 되는데요. 이 과정이 부자연 스러워서 보통 QA 티켓으로 발급되었습니다.

사용자 입장에서는 이 사소한 부분이 결함이라고 오해할 수 있고, 이 사소한 결함들이 누적되면 웹사이트의 품질이 저하 되는 경험을 할 수 있기 때문에 불가피하게 수정 조치해야 하는 경우가 있습니다.

## 스크롤바 감추는 CSS 코드

스크롤바의 기능을 유지하면서 스크롤바의 형태를 감추기 위해 사용하는 코드입니다.

```css
/* Chrome, Safari, Opera */
.hide-scrollbar::-webkit-scrollbar {
  width: 0;
} 

.hide-scrollbar {
    /* Firefox */
  scrollbar-width: none;

  /* Internet Explorer, Edge */
  -ms-overflow-style: none;
}
```

이 유틸리티 클래스를 만들어 놓고, 스크롤바를 제거해야할 때만 활용하는 CSS 유틸리티 클래스입니다. 빈번하게 사용하지 않지만 개인적으로 특수한 경우에만 사용하고 있고, 가능하면 사용을 지양하는 편입니다.

## 출처

https://stackoverflow.com/questions/38643271/hide-scrollbar-in-firefox-and-edge?noredirect=1&lq=1
